Ko/raport
MichaelStett/2021_AI1 pull request #29
Opened 2021-01-11 09:20 UTC by firyan4

2021-01-11 21:40 UTC, darpek123 approved these changes

2021-01-11 21:54 UTC, Szwarceneger16 requested changes
nalezy utrzymać responsywnośc zgodnie z bootsrtapem
https://getbootstrap.com/docs/4.5/layout/grid/
proszę utworzyć osobny wiersz i kolumny i dokleic to w którymś miejscu

2021-01-12 12:38 UTC, MichaelStett requested changes
Dużo do poprawy :(

2021-01-12 12:38 UTC, MichaelStett commented on models/contact.html
> +<!DOCTYPE html>
folder models i masz w nim plik html? o co tu chodzi?

2021-01-12 12:38 UTC, MichaelStett commented on models/InvoiceSale.php
> +
puste linijki?

2021-01-12 12:38 UTC, MichaelStett commented on raport/invoice-db-form.php
> +		<form method='get' action='invoice-db.php'>
Trzeba to przenieść do widoku

2021-01-12 12:38 UTC, MichaelStett commented on raport/invoice-db.php
> +$con=mysqli_connect('localhost','root','');
Powinnaś to przenieść do jakiegoś nowego repository i używać $config do łaczenia się i pobierania danych z bazy

2021-01-12 12:38 UTC, MichaelStett commented on raport/invoice-form.php
> +		<form method='post' action='invoice-result.php'>
Zrób widok!

2021-01-12 12:38 UTC, MichaelStett commented on raport/invoice-result.php
> +$pdf = new FPDF('P','mm','A4');
Do robienia tych raportów najlepiej byłoby zrobić klase w której byłaby cała logika

2021-01-12 12:38 UTC, MichaelStett commented on views/Layout.php
> +
puste linie?

2021-01-12 15:24 UTC, Szwarceneger16 approved these changes
na slepo pozniej sie poprawi

2021-01-18 19:39 UTC, closed without merging